version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: music2.0_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: music
    ports:
      - '5432:5432'
    volumes:
      - music2_data:/var/lib/postgresql/data

volumes:
  music2_data:
