name: backend deploy

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          node-version: 20.x.x
          cache: npm

  deploy:
    needs: lint
    runs-on: ubuntu-latest
    concurrency:
      group: staging
      cancel-in-progress: true
    steps:
      - name: SSH Command
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{ secrets.STAGING_SSH_HOST }}
          user: ${{ secrets.STAGING_SSH_USERNAME }}
          private_key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          host_fingerprint: ${{ secrets.STAGING_SSH_FINGERPRINT }}
          command: source ~/.nvm/nvm.sh; ~/backend-deploy.sh
